version: "3.8"

services:
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    volumes:
      - .:/project
      - node_modules:/project/node_modules/
    depends_on:
      - redis

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.2-alpine3.18
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  node_modules:
  cache:
    driver: local
